// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: clusters.proto

package clusters

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClusterOrder_Type int32

const (
	CreateClusterOrder_DOCKER_SWARM       CreateClusterOrder_Type = 0
	CreateClusterOrder_KUBERNETES_CLUSTER CreateClusterOrder_Type = 1
	CreateClusterOrder_PODMAN_SWARM       CreateClusterOrder_Type = 2
)

// Enum value maps for CreateClusterOrder_Type.
var (
	CreateClusterOrder_Type_name = map[int32]string{
		0: "DOCKER_SWARM",
		1: "KUBERNETES_CLUSTER",
		2: "PODMAN_SWARM",
	}
	CreateClusterOrder_Type_value = map[string]int32{
		"DOCKER_SWARM":       0,
		"KUBERNETES_CLUSTER": 1,
		"PODMAN_SWARM":       2,
	}
)

func (x CreateClusterOrder_Type) Enum() *CreateClusterOrder_Type {
	p := new(CreateClusterOrder_Type)
	*p = x
	return p
}

func (x CreateClusterOrder_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateClusterOrder_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_clusters_proto_enumTypes[0].Descriptor()
}

func (CreateClusterOrder_Type) Type() protoreflect.EnumType {
	return &file_clusters_proto_enumTypes[0]
}

func (x CreateClusterOrder_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateClusterOrder_Type.Descriptor instead.
func (CreateClusterOrder_Type) EnumDescriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{0, 0}
}

type CreateClusterOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Teams       []string                `protobuf:"bytes,3,rep,name=teams,proto3" json:"teams,omitempty"`
	Type        CreateClusterOrder_Type `protobuf:"varint,4,opt,name=type,proto3,enum=CreateClusterOrder_Type" json:"type,omitempty"`
	Namespace   string                  `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Address     string                  `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CreateClusterOrder) Reset() {
	*x = CreateClusterOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clusters_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClusterOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterOrder) ProtoMessage() {}

func (x *CreateClusterOrder) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterOrder.ProtoReflect.Descriptor instead.
func (*CreateClusterOrder) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClusterOrder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterOrder) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateClusterOrder) GetTeams() []string {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *CreateClusterOrder) GetType() CreateClusterOrder_Type {
	if x != nil {
		return x.Type
	}
	return CreateClusterOrder_DOCKER_SWARM
}

func (x *CreateClusterOrder) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateClusterOrder) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdateClusterOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Teams       []string `protobuf:"bytes,3,rep,name=teams,proto3" json:"teams,omitempty"`
}

func (x *UpdateClusterOrder) Reset() {
	*x = UpdateClusterOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clusters_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateClusterOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterOrder) ProtoMessage() {}

func (x *UpdateClusterOrder) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterOrder.ProtoReflect.Descriptor instead.
func (*UpdateClusterOrder) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateClusterOrder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateClusterOrder) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateClusterOrder) GetTeams() []string {
	if x != nil {
		return x.Teams
	}
	return nil
}

type NodeDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *NodeDetails) Reset() {
	*x = NodeDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clusters_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDetails) ProtoMessage() {}

func (x *NodeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDetails.ProtoReflect.Descriptor instead.
func (*NodeDetails) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{2}
}

func (x *NodeDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ClusterDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address   string         `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Type      string         `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Teams     []string       `protobuf:"bytes,4,rep,name=teams,proto3" json:"teams,omitempty"`
	Namespace string         `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Nodes     []*NodeDetails `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ClusterDetails) Reset() {
	*x = ClusterDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clusters_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterDetails) ProtoMessage() {}

func (x *ClusterDetails) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterDetails.ProtoReflect.Descriptor instead.
func (*ClusterDetails) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClusterDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClusterDetails) GetTeams() []string {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ClusterDetails) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ClusterDetails) GetNodes() []*NodeDetails {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Clusters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ClusterDetails `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Clusters) Reset() {
	*x = Clusters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clusters_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clusters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clusters) ProtoMessage() {}

func (x *Clusters) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clusters.ProtoReflect.Descriptor instead.
func (*Clusters) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{4}
}

func (x *Clusters) GetEntries() []*ClusterDetails {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_clusters_proto protoreflect.FileDescriptor

var file_clusters_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8a, 0x02, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65,
	0x61, 0x6d, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x42, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x4f, 0x43, 0x4b, 0x45, 0x52, 0x5f, 0x53, 0x57, 0x41, 0x52,
	0x4d, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4b, 0x55, 0x42, 0x45, 0x52, 0x4e, 0x45, 0x54, 0x45,
	0x53, 0x5f, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x50,
	0x4f, 0x44, 0x4d, 0x41, 0x4e, 0x5f, 0x53, 0x57, 0x41, 0x52, 0x4d, 0x10, 0x02, 0x22, 0x60, 0x0a,
	0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x61,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x22,
	0x4f, 0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0xaa, 0x01, 0x0a, 0x0e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x35, 0x0a,
	0x08, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clusters_proto_rawDescOnce sync.Once
	file_clusters_proto_rawDescData = file_clusters_proto_rawDesc
)

func file_clusters_proto_rawDescGZIP() []byte {
	file_clusters_proto_rawDescOnce.Do(func() {
		file_clusters_proto_rawDescData = protoimpl.X.CompressGZIP(file_clusters_proto_rawDescData)
	})
	return file_clusters_proto_rawDescData
}

var file_clusters_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clusters_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_clusters_proto_goTypes = []interface{}{
	(CreateClusterOrder_Type)(0), // 0: CreateClusterOrder.Type
	(*CreateClusterOrder)(nil),   // 1: CreateClusterOrder
	(*UpdateClusterOrder)(nil),   // 2: UpdateClusterOrder
	(*NodeDetails)(nil),          // 3: NodeDetails
	(*ClusterDetails)(nil),       // 4: ClusterDetails
	(*Clusters)(nil),             // 5: Clusters
}
var file_clusters_proto_depIdxs = []int32{
	0, // 0: CreateClusterOrder.type:type_name -> CreateClusterOrder.Type
	3, // 1: ClusterDetails.nodes:type_name -> NodeDetails
	4, // 2: Clusters.entries:type_name -> ClusterDetails
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_clusters_proto_init() }
func file_clusters_proto_init() {
	if File_clusters_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clusters_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClusterOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clusters_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateClusterOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clusters_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clusters_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clusters_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Clusters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clusters_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clusters_proto_goTypes,
		DependencyIndexes: file_clusters_proto_depIdxs,
		EnumInfos:         file_clusters_proto_enumTypes,
		MessageInfos:      file_clusters_proto_msgTypes,
	}.Build()
	File_clusters_proto = out.File
	file_clusters_proto_rawDesc = nil
	file_clusters_proto_goTypes = nil
	file_clusters_proto_depIdxs = nil
}
