provider: DOCKER-SWARM
profile-directory: /etc/aurora # Path on file system to good stuff
default-cluster: default # BECAUSE YOU SUCK
default-cluster-listen-address: 0.0.0.0:2377
default-cluster-advertise-address: 10.7.96.4
default-team: admin
domain: kanika.app # USE YOU OWN DOMAIN
admin-session-duration: 24 # HOURS
host: 0.0.0.0
port: 3000
cert-resolver: "letsencrypt"
encryption:
  memory: 65536
  iterations: 4
  parallelism: 2
  salt-length: 16
  key-length: 32