// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.3
// source: apps.proto

package apps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryCredentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Temporary bool   `protobuf:"varint,3,opt,name=temporary,proto3" json:"temporary,omitempty"`
}

func (x *RegistryCredentials) Reset() {
	*x = RegistryCredentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistryCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCredentials) ProtoMessage() {}

func (x *RegistryCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCredentials.ProtoReflect.Descriptor instead.
func (*RegistryCredentials) Descriptor() ([]byte, []int) {
	return file_apps_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryCredentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistryCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistryCredentials) GetTemporary() bool {
	if x != nil {
		return x.Temporary
	}
	return false
}

type DeploymentPass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Token      []byte `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *DeploymentPass) Reset() {
	*x = DeploymentPass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploymentPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentPass) ProtoMessage() {}

func (x *DeploymentPass) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentPass.ProtoReflect.Descriptor instead.
func (*DeploymentPass) Descriptor() ([]byte, []int) {
	return file_apps_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentPass) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *DeploymentPass) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type CreateAppOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Cluster     string `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Team        string `protobuf:"bytes,4,opt,name=team,proto3" json:"team,omitempty"`
	Scale       int32  `protobuf:"varint,5,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *CreateAppOrder) Reset() {
	*x = CreateAppOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppOrder) ProtoMessage() {}

func (x *CreateAppOrder) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppOrder.ProtoReflect.Descriptor instead.
func (*CreateAppOrder) Descriptor() ([]byte, []int) {
	return file_apps_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAppOrder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAppOrder) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAppOrder) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *CreateAppOrder) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *CreateAppOrder) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type UpdateAppOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Scale       int32  `protobuf:"varint,3,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *UpdateAppOrder) Reset() {
	*x = UpdateAppOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAppOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppOrder) ProtoMessage() {}

func (x *UpdateAppOrder) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppOrder.ProtoReflect.Descriptor instead.
func (*UpdateAppOrder) Descriptor() ([]byte, []int) {
	return file_apps_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAppOrder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAppOrder) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAppOrder) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type DeployAppOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUri    string               `protobuf:"bytes,2,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	Credentials *RegistryCredentials `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
}

func (x *DeployAppOrder) Reset() {
	*x = DeployAppOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployAppOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppOrder) ProtoMessage() {}

func (x *DeployAppOrder) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppOrder.ProtoReflect.Descriptor instead.
func (*DeployAppOrder) Descriptor() ([]byte, []int) {
	return file_apps_proto_rawDescGZIP(), []int{4}
}

func (x *DeployAppOrder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployAppOrder) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *DeployAppOrder) GetCredentials() *RegistryCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type AppDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Team        string            `protobuf:"bytes,3,opt,name=team,proto3" json:"team,omitempty"`
	Cluster     string            `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Containers  []*ContainerEntry `protobuf:"bytes,5,rep,name=containers,proto3" json:"containers,omitempty"`
}

func (x *AppDetails) Reset() {
	*x = AppDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDetails) ProtoMessage() {}

func (x *AppDetails) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDetails.ProtoReflect.Descriptor instead.
func (*AppDetails) Descriptor() ([]byte, []int) {
	return file_apps_proto_rawDescGZIP(), []int{5}
}

func (x *AppDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppDetails) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *AppDetails) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *AppDetails) GetContainers() []*ContainerEntry {
	if x != nil {
		return x.Containers
	}
	return nil
}

type AppEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scale int32  `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *AppEntry) Reset() {
	*x = AppEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppEntry) ProtoMessage() {}

func (x *AppEntry) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppEntry.ProtoReflect.Descriptor instead.
func (*AppEntry) Descriptor() ([]byte, []int) {
	return file_apps_proto_rawDescGZIP(), []int{6}
}

func (x *AppEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppEntry) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type ContainerEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Ip         string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Family     int32  `protobuf:"varint,3,opt,name=family,proto3" json:"family,omitempty"`
}

func (x *ContainerEntry) Reset() {
	*x = ContainerEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEntry) ProtoMessage() {}

func (x *ContainerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEntry.ProtoReflect.Descriptor instead.
func (*ContainerEntry) Descriptor() ([]byte, []int) {
	return file_apps_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerEntry) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ContainerEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ContainerEntry) GetFamily() int32 {
	if x != nil {
		return x.Family
	}
	return 0
}

type AppSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry []*AppEntry `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
}

func (x *AppSummary) Reset() {
	*x = AppSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSummary) ProtoMessage() {}

func (x *AppSummary) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSummary.ProtoReflect.Descriptor instead.
func (*AppSummary) Descriptor() ([]byte, []int) {
	return file_apps_proto_rawDescGZIP(), []int{8}
}

func (x *AppSummary) GetEntry() []*AppEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_apps_proto protoreflect.FileDescriptor

var file_apps_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x13,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x22, 0x46, 0x0a, 0x0e, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x5c,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x79, 0x0a, 0x0e,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x41, 0x70, 0x70, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x69, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x12,
	0x36, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x34, 0x0a, 0x08, 0x41,
	0x70, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x22, 0x58, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x22, 0x2d, 0x0a, 0x0a, 0x41,
	0x70, 0x70, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x70, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b,
	0x61, 0x70, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_proto_rawDescOnce sync.Once
	file_apps_proto_rawDescData = file_apps_proto_rawDesc
)

func file_apps_proto_rawDescGZIP() []byte {
	file_apps_proto_rawDescOnce.Do(func() {
		file_apps_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_proto_rawDescData)
	})
	return file_apps_proto_rawDescData
}

var file_apps_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_apps_proto_goTypes = []interface{}{
	(*RegistryCredentials)(nil), // 0: RegistryCredentials
	(*DeploymentPass)(nil),      // 1: DeploymentPass
	(*CreateAppOrder)(nil),      // 2: CreateAppOrder
	(*UpdateAppOrder)(nil),      // 3: UpdateAppOrder
	(*DeployAppOrder)(nil),      // 4: DeployAppOrder
	(*AppDetails)(nil),          // 5: AppDetails
	(*AppEntry)(nil),            // 6: AppEntry
	(*ContainerEntry)(nil),      // 7: ContainerEntry
	(*AppSummary)(nil),          // 8: AppSummary
}
var file_apps_proto_depIdxs = []int32{
	0, // 0: DeployAppOrder.credentials:type_name -> RegistryCredentials
	7, // 1: AppDetails.containers:type_name -> ContainerEntry
	6, // 2: AppSummary.entry:type_name -> AppEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_apps_proto_init() }
func file_apps_proto_init() {
	if File_apps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistryCredentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploymentPass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAppOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployAppOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_proto_goTypes,
		DependencyIndexes: file_apps_proto_depIdxs,
		MessageInfos:      file_apps_proto_msgTypes,
	}.Build()
	File_apps_proto = out.File
	file_apps_proto_rawDesc = nil
	file_apps_proto_goTypes = nil
	file_apps_proto_depIdxs = nil
}
